name: grounding_dino
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.39
  - binutils_linux-64=2.39
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cudatoolkit=11.3.1
  - gcc_impl_linux-64=9.5.0
  - gcc_linux-64=9.5.0
  - gxx_impl_linux-64=9.5.0
  - gxx_linux-64=9.5.0
  - kernel-headers_linux-64=3.10.0
  - ld_impl_linux-64=2.39
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-devel_linux-64=9.5.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libsanitizer=9.5.0
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=9.5.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.9.21
  - readline=8.2
  - setuptools=75.8.2
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - wheel=0.45.1
  - pip:      
      - absl-py==2.2.0
      - addict==2.4.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - black==25.1.0
      - bleach==6.2.0
      - bs4==0.0.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - detectron2==0.6
      - evaluation==0.0.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fonttools==4.56.0
      - fqdn==1.5.1
      - fsspec==2025.3.0
      - fvcore==0.1.5.post20221221
      - glog==0.3.1
      - grpcio==1.71.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.29.3
      - hydra-core==1.3.2
      - icrawler==0.6.10
      - idna==3.10
      - imageio==2.37.0
      - img-utils==0.0.13
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - iopath==0.1.9
      - ipykernel==6.29.5
      - ipython==8.18.1
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning-utilities==0.14.3
      - lxml==5.3.2
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - mobile-sam==1.0
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - notebook==7.4.3
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.7
      - portalocker==3.1.1
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.50
      - protobuf==6.30.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pycocotools==2.0.8
      - pycparser==2.22
      - pygments==2.19.1
      - pyparsing==3.2.2
      - python-dateutil==2.9.0.post0
      - python-gflags==3.1.2
      - python-json-logger==3.3.0
      - pytorch-triton==3.2.0+git4b3bb1f8
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.25.1
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - segment-anything==1.0
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - supervision==0.25.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - terminado==0.18.1
      - tifffile==2024.8.30
      - timm==1.0.15
      - tinycss2==1.4.0
      - tokenizers==0.15.2
      - tomli==2.2.1
      - torch==2.2.0+cu121
      - torchaudio==2.2.0+cu121
      - torchmetrics==1.2.1
      - torchvision==0.17.0+cu121
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.38.2
      - triton==2.2.0
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - ultralytics==8.3.109
      - ultralytics-thop==2.0.14
      - uri-template==1.3.0
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - yacs==0.1.8
      - yapf==0.43.0
      - zipp==3.21.0

